In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file = '/content/drive/MyDrive/Project/EPC/powerconsumption.csv'

In [ ]:
# dataset utama
df = pd.read_csv(file)

In [ ]:
df.head()

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

In [ ]:
# mengubah kolom Datetime menjadi format tanggal
df['Datetime'] = pd.to_datetime(df['Datetime'])

In [ ]:
# menghitung total penggunaan listrik
df['Total_Power_Consumption'] = (
    df['PowerConsumption_Zone1'] +
    df['PowerConsumption_Zone2'] +
    df['PowerConsumption_Zone3'])

In [ ]:
# Aggregasi data per 10 menit menjadi Rata-Rata per Jam (Hourly)
df_hourly = df.resample('1h', on='Datetime').mean().reset_index()

In [ ]:
# menambah kolom (Hour, Month, Day_Name, Is_Weekend) sebagai kolom pendukung
df_hourly['Hour'] = df_hourly['Datetime'].dt.hour
df_hourly['Month'] = df_hourly['Datetime'].dt.month_name()
df_hourly['Day_Name'] = df_hourly['Datetime'].dt.day_name()
df_hourly['Is_Weekend'] = df_hourly['Datetime'].dt.dayofweek.isin([5, 6]).map({True: 'Weekend', False: 'Weekday'})

In [ ]:
# lihat hasil
df_hourly.head()

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3,Total_Power_Consumption,Hour,Month,Day_Name,Is_Weekend
0,2017-01-01 00:00:00,6.196833,75.066667,0.081833,0.063500,0.098833,29197.974683,18026.747720,19252.048193,66476.770597,0,January,Sunday,Weekend
1,2017-01-01 01:00:00,5.548833,77.583333,0.082000,0.056833,0.112500,24657.215190,16078.419453,17042.891567,57778.526210,1,January,Sunday,Weekend
2,2017-01-01 02:00:00,5.054333,78.933333,0.082333,0.063000,0.129167,22083.037973,14330.699088,15676.144578,52089.881640,2,January,Sunday,Weekend
3,2017-01-01 03:00:00,5.004333,77.083333,0.082833,0.059833,0.141000,20811.139240,13219.452887,14883.855422,48914.447548,3,January,Sunday,Weekend
4,2017-01-01 04:00:00,5.097667,74.050000,0.082333,0.058000,0.122833,20475.949367,12921.580547,14317.108433,47714.638347,4,January,Sunday,Weekend

In [ ]:
# save file
df_hourly.to_csv('power_consumption_cleaned.csv', index=False)